development:
  adapter: postgresql
  database: emotecloud_development
  host: localhost

test:
  adapter: postgresql
  database: emotecloud_test
  host: localhost

production:
  adapter: postgresql
  database: emotecloud_production
  username: emotecloud
  password: <%= ENV['POSTGRES_PASS'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: 50
